### ISSUE TITLE
Error Exception: System.FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by ronusco** [DigitalRuby/IPBan#122]
2021-01-05 00:03:22.9574|ERROR|DigitalRuby.IPBanCore.Logger|Error Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt64(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt64(IFormatProvider provider)
   at DigitalRuby.IPBanCore.IPBanDB.ParseIPAddressEntry(SqliteDataReader reader)
   at DigitalRuby.IPBanCore.IPBanDB.EnumerateIPAddresses(Nullable`1 failLoginCutOff, Nullable`1 banCutOff, Object transaction)+MoveNext()
   at DigitalRuby.IPBanCore.IPBanService.HandleWhitelistChanged(Object transaction, HashSet`1 unbanList)
   at DigitalRuby.IPBanCore.IPBanService.UpdateExpiredIPAddressStates()
2021-01-05 00:08:24.0404|ERROR|DigitalRuby.IPBanCore.Logger|Error Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt64(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt64(IFormatProvider provider)
   at DigitalRuby.IPBanCore.IPBanDB.ParseIPAddressEntry(SqliteDataReader reader)
   at DigitalRuby.IPBanCore.IPBanDB.EnumerateIPAddresses(Nullable`1 failLoginCutOff, Nullable`1 banCutOff, Object transaction)+MoveNext()
   at DigitalRuby.IPBanCore.IPBanService.HandleWhitelistChanged(Object transaction, HashSet`1 unbanList)
   at DigitalRuby.IPBanCore.IPBanService.UpdateExpiredIPAddressStates()

**Comment by jjxtra** [comment]
Can you send me your ipban.sqlite file to support@digitalruby.com?

**Comment by jjxtra** [comment]
Just FYI I'm adding a try/catch around this conversion with an info log in the future so it won't crash out of the white list processor
