### ISSUE TITLE
ipban.override.config problems?

### ISSUE THREAD

**Issue by Hartwin2342** [DigitalRuby/IPBan#125]
I wanted to start using the override config because there is a chance of overwritten configs after installation of new versions.

Since I pasted some key/value to the right place and saved the file, I got the following logfile entries:

2021-01-10 07:54:35.2050|ERROR|DigitalRuby.IPBanCore.Logger|Error Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DigitalRuby.IPBanCore.IPBanService.MergeXml(String xmlBase, String xmlOverride)
   at DigitalRuby.IPBanCore.IPBanService.UpdateConfiguration()

2021-01-10 07:59:38.4384|ERROR|DigitalRuby.IPBanCore.Logger|Error Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DigitalRuby.IPBanCore.IPBanService.MergeXml(String xmlBase, String xmlOverride)
   at DigitalRuby.IPBanCore.IPBanService.UpdateConfiguration()

2021-01-10 08:04:41.5662|ERROR|DigitalRuby.IPBanCore.Logger|Error Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DigitalRuby.IPBanCore.IPBanService.MergeXml(String xmlBase, String xmlOverride)
   at DigitalRuby.IPBanCore.IPBanService.UpdateConfiguration()

2021-01-10 08:09:44.7496|ERROR|DigitalRuby.IPBanCore.Logger|Error Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DigitalRuby.IPBanCore.IPBanService.MergeXml(String xmlBase, String xmlOverride)
   at DigitalRuby.IPBanCore.IPBanService.UpdateConfiguration()

As you can see, every 5 min. the next logentry.

Is this a bug or is it my fault?

**Comment by jjxtra** [comment]
Sounds like you may have deleted some of the elements. The code expects all the elements to exist even if empty. I will re-upload a 1.5.9 version that does some more null checks. Try downloading it in about 30 minutes and let me know if it helps.

**Comment by Hartwin2342** [comment]
No, it does not help.
I did not delete any line or caracter from the original ipban.override.config.
I simply pasted some content from ipban.config to the override file (including comments). I placed the pasted lines between `<appSettings>` and `</appSettings>` like it is placed in ipban.config.

BTW: the installerscript replaced my old override file with an empty one. The ipban.config kept untouched. In my imagination, it sould work exactly the opposite way (keep the override untouched, rewrite the config to introduce new keys).

**Comment by jjxtra** [comment]
Can you post your override config? Feel free to mask any sensitive info.

**Comment by Hartwin2342** [comment]
> Can you post your override config? Feel free to mask any sensitive info.

can't paste it. It will be modified by the editor. Sent it as attachement.

[ipban.override.config.txt](https://github.com/DigitalRuby/IPBan/files/5799936/ipban.override.config.txt)

**Comment by jjxtra** [comment]
Looks like it was the comment throwing it off. I will re-upload a 1.5.9 version. Try in about an hour.

**Comment by Hartwin2342** [comment]
OK.
No new Errors anymore. Thanks a lot. Now the closed-button no longer lies.
