### ISSUE TITLE
XML error log spam

### ISSUE THREAD

**Issue by pwn0r** [DigitalRuby/IPBan#161]
```
|ERROR|DigitalRuby.IPBanCore.Logger|Failed to load log files from xml: System.InvalidOperationException: There is an error in the XML document.
 ---> System.Xml.XmlException: Unexpected node type Comment. ReadElementString method can only be called on elements with simple or empty content.
   at System.Xml.XmlReader.ReadElementString()
   at DigitalRuby.IPBanCore.XmlCData.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderIPBanLogFilesToParse.Read3_IPBanLogFileToParse(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderIPBanLogFilesToParse.Read4_IPBanLogFilesToParse(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderIPBanLogFilesToParse.Read5_LogFilesToParse()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at DigitalRuby.IPBanCore.IPBanConfig.ParseLogFiles(XmlDocument doc, String path)---
```

I get constant spamming of this error in the log files. Thing is even if it something wrong e.g. in a config file, this error message is not clear where exactly is the problem. 

Machine I'm running this on is a server 2019 full installation, i.e. not a core install.

**Comment by jjxtra** [comment]
This is a default install with no config changes?

**Comment by pwn0r** [comment]
Hello, I think I fixed it now.
The problem however was not my modifications, i only did a couple of changes like for ban duration etc. I only use this for RDP services. 

I downloaded a recent release a few months ago, and updated it in place, but not the config. Apparently they have quite a number of differences. So I guess this was causing the log spam.
