### ISSUE TITLE
System.MissingMethodException in log

### ISSUE THREAD

**Issue by bachratyg** [DigitalRuby/IPBan#169]
I have some exceptions in the log (1-2 entries every couple of days):
```
Error determining if user is active: System.MissingMethodException: Cannot dynamically create an instance of type 'System.Management.WbemDefPath'. Reason: No parameterless constructor defined.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType )
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
   at System.Activator.CreateInstance(Type type)
   at System.Management.MTAHelper.CreateInMTA(Type )
   at System.Management.ManagementPath.CreateWbemPath(String )
   at System.Management.ManagementPath..ctor(String path)
   at System.Management.SelectQuery..ctor(String )
   at DigitalRuby.IPBanCore.OSUtility.UserIsActive(String userName) in C:\Users\Jeff\Documents\GitHub\DigitalRuby\IPBan\IPBanCore\Core\Utility\OSUtility.cs:line 441
```
Banning login attempts seem to work otherwise.

Version: 1.7.0 (windows-x64)
OS: Win10 21H1

**Comment by jjxtra** [comment]
When did you download the zip? I did an update a day or two ago that might fix this error.

**Comment by bachratyg** [comment]
About two weeks ago. I just checked the logs today to see if there's anything interesting.

The current zip is definitely different from what I have. I'm going to install the new version then report back in a couple of days if the problem persists.

**Comment by bachratyg** [comment]
No error in the log for 7 days straight. The new version fixed the problem.

**Comment by jjxtra** [comment]
Glad to hear.
