### ISSUE TITLE
The information requested is unavailable on the current platform

### ISSUE THREAD

**Issue by dannykorpan** [DigitalRuby/IPBan#232]
Hi,

after installing IPBan 1.8.0 on Ubuntu 20.04.5 I get the following error via systemctl status ipban
````
Dec 01 16:50:46 v220210216069144653 DigitalRuby.IPBan[1453946]: 2022-12-01 16:50:46.4745|WARN|IPBan|Updating firewall with 0 entries...
Dec 01 16:50:46 v220210216069144653 DigitalRuby.IPBan[1453946]: 2022-12-01 16:50:46.4745|INFO|IPBan|Firewall entries updated:
Dec 01 16:50:46 v220210216069144653 DigitalRuby.IPBan[1453946]: 2022-12-01 16:50:46.5452|WARN|IPBan|IPBan is running correctly. You can perform a failed ssh or rdp login and watch this log to verify functionality.
Dec 01 16:51:01 v220210216069144653 DigitalRuby.IPBan[1453946]: 2022-12-01 16:51:01.5535|ERROR|IPBan|Error Exception: System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
Dec 01 16:51:01 v220210216069144653 DigitalRuby.IPBan[1453946]:    at System.Net.NetworkInformation.UnixIPInterfaceProperties.get_DnsAddresses()
Dec 01 16:51:01 v220210216069144653 DigitalRuby.IPBan[1453946]:    at DigitalRuby.IPBanCore.NetworkUtility.GetLocalDnsServers()
Dec 01 16:51:01 v220210216069144653 DigitalRuby.IPBan[1453946]:    at DigitalRuby.IPBanCore.IPBanDnsServerList.UpdateDnsServersIfNeeded()
````

Using the ouf of the box ipban.conf

Any suggestions?

Thanks in advance,
Danny

**Comment by jjxtra** [comment]
Does your server have a dns entry setup for the network interface?

**Comment by dannykorpan** [comment]
Yes

> Does your server have a dns entry setup for the network interface?

**Comment by jjxtra** [comment]
Tried on several of my Ubuntu servers and did not see the error. Do you have other Ubuntu server you could try on?

**Comment by dannykorpan** [comment]
Hi, works on other machine.
