### ISSUE TITLE
Error in sending ip to Abuseipdb

### ISSUE THREAD

**Issue by gotspatel** [DigitalRuby/IPBan#237]
Getting error as below

2023-01-10 16:57:20.5765|ERROR|IPBan|Failed to execute process C:\IPBan\report_abuse_db.ps1 xxx.xxx.xxx.xxx: System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'C:\IPBan\report_abuse_db.ps1' with working directory 'C:\IPBan'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo )
   at System.Diagnostics.Process.StartCore(ProcessStartInfo )
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo )
   at DigitalRuby.IPBanCore.IPBanService.<>c__DisplayClass190_1.<ExecuteExternalProcessForIPAddresses>b__0()

what may be wrong. I have tried the powershell script from console it is working okay but not working with ipban

in the config file I have

add key="ProcessToRunOnBan" value="report_abuse_db.ps1|###IPADDRESS###"/

**Comment by jjxtra** [comment]
It may be easier to use the ipthreat integration. I don't maintain the abuse ip db scripts.

**Comment by jjxtra** [comment]
https://ipthreat.net/integrations/ipban
