### ISSUE TITLE
FirewallUriRules Error (Last 2 refreshed downloads for 2.0.0)

### ISSUE THREAD

**Issue by RvdHout** [DigitalRuby/IPBan#302]
**ipban.override.config** excerpt

```
    <!--
      External firewall uri rules to block, format is (one per line):
      [RulePrefix],[Interval in DD:HH:MM:SS],[URI][Newline]
	-->
	<add key="FirewallUriRules" value="
		AbuseIPDB,00:01:00:00,file://C:\Program Files\IPBan\abuseipdb_blacklist.txt
		EmergingThreats,01:00:00:00,https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt
		IPThreat,01:00:00:00,https://lists.ipthreat.net/file/ipthreat-lists/threat/threat-0.txt.gz,10000
	"/>
```

There seems to be a forward slash automatically appended to the URL. eg:

https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt/

and 

https://lists.ipthreat.net/file/ipthreat-lists/threat/threat-0.txt.gz/

As you can see the AbuseIPDB list (which is a file locally) is loaded correctly

**log**

```
2024-05-24 14:50:14.0323|WARN|IPBan|Updating firewall uri rule AbuseIPDB with 8776 ips
2024-05-24 14:50:14.5016|ERROR|IPBan|Error in updater DigitalRuby.IPBanCore.IPBanUriFirewallRule: System.Net.Http.HttpRequestException: Request to url https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt/ failed, status: NotFound, response: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

   at DigitalRuby.IPBanCore.DefaultHttpRequestMaker.MakeRequestAsync(Uri uri, Byte[] postJson, IEnumerable`1 headers, String method, CancellationToken cancelToken)
   at DigitalRuby.IPBanCore.IPBanUriFirewallRule.Update(CancellationToken cancelToken)
   at DigitalRuby.IPBanCore.IPBanService.UpdateUpdaters(CancellationToken cancelToken)
2024-05-24 14:50:15.0195|ERROR|IPBan|Error in updater DigitalRuby.IPBanCore.IPBanUriFirewallRule: System.Net.Http.HttpRequestException: Request to url https://lists.ipthreat.net/file/ipthreat-lists/threat/threat-0.txt.gz/ failed, status: NotFound, response: {
  "code": "not_found",
  "message": "File with such name does not exist.",
  "status": 404
}
   at DigitalRuby.IPBanCore.DefaultHttpRequestMaker.MakeRequestAsync(Uri uri, Byte[] postJson, IEnumerable`1 headers, String method, CancellationToken cancelToken)
   at DigitalRuby.IPBanCore.IPBanUriFirewallRule.Update(CancellationToken cancelToken)
   at DigitalRuby.IPBanCore.IPBanService.UpdateUpdaters(CancellationToken cancelToken)
```

If i go back to 2.0.0 downloaded early in May i get no such errors

**Comment by jjxtra** [comment]
Have refreshed the release. Let me know if it's any better.

**Comment by RvdHout** [comment]
Yep that fixes it, thx! (this issue can be closed)
