### ISSUE TITLE
Compatibility windows server 2025

### ISSUE THREAD

**Issue by fhm20** [DigitalRuby/IPBan#310]
I am testing IPBan with Windows Server 2025 Preview. This version of Windows does not have the wmic command.

Windows Management Instrumentation Command line (WMIC)
Beginning with Windows Server 2025, WMIC is available as a feature on demand (FoD) which can be added with the DISM /Add-Capability command. It will be removed from Windows in a future release. PowerShell for WMI replaces the WMIC tool. Use PowerShell or programmatically query WMI as a replacement for WMIC. To learn more about WMIC depreciation, see WMI command line (WMIC) utility deprecation.
https://learn.microsoft.com/en-us/windows-server/get-started/removed-deprecated-features-windows-server-2025

In the logs, this message is shown but no error appears:
2024-09-10 12:17:51.9815|INFO|IPBan|Executing process wmic useraccount get disabled,name...

Could you review the operation of IPBan to adapt it to Windows Server 2025?

Thanks

**Comment by jjxtra** [comment]
Thanks for brining to my attention. I'll remove wmic command and find another way.

**Comment by jjxtra** [comment]
Attempted fix: d62b8aba4927c15ba09d263e0316a9e2da5f9b44
Release: https://github.com/DigitalRuby/IPBan/releases/tag/2.0.1

@fhm20 Please verify on your Server 2025 machine and report back.

**Comment by fhm20** [comment]
The new version doesn't work.
When I make the first login attempt, I get an error and the service restarts.

Application: DigitalRuby.IPBan.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at System.DirectoryServices.UnsafeNativeMethods+IAds.GetInfo()
   at System.DirectoryServices.UnsafeNativeMethods+IAds.GetInfo()
   at System.DirectoryServices.DirectoryEntry.RefreshCache()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.PrincipalSearcher.SetDefaultPageSizeForContext()
   at System.DirectoryServices.AccountManagement.PrincipalSearcher..ctor(System.DirectoryServices.AccountManagement.Principal)
   at DigitalRuby.IPBanCore.OSUtility.PopulateUsersWindows(System.Collections.Generic.Dictionary`2<System.String,Boolean>)
   at DigitalRuby.IPBanCore.OSUtility.UserIsActive(System.String)
   at DigitalRuby.IPBanCore.IPBanService+<ProcessPendingFailedLogins>d__191.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[DigitalRuby.IPBanCore.IPBanService+<ProcessPendingFailedLogins>d__191, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]](<ProcessPendingFailedLogins>d__191 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[DigitalRuby.IPBanCore.IPBanService+<ProcessPendingFailedLogins>d__191, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]](<ProcessPendingFailedLogins>d__191 ByRef)
   at DigitalRuby.IPBanCore.IPBanService.ProcessPendingFailedLogins(System.Collections.Generic.IReadOnlyList`1<DigitalRuby.IPBanCore.IPAddressLogEvent>, System.Threading.CancellationToken)
   at DigitalRuby.IPBanCore.IPBanService+<ProcessPendingFailedLogins>d__214.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[DigitalRuby.IPBanCore.IPBanService+<ProcessPendingFailedLogins>d__214, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]](<ProcessPendingFailedLogins>d__214 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[DigitalRuby.IPBanCore.IPBanService+<ProcessPendingFailedLogins>d__214, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]](<ProcessPendingFailedLogins>d__214 ByRef)
   at DigitalRuby.IPBanCore.IPBanService.ProcessPendingFailedLogins(System.Threading.CancellationToken)
   at DigitalRuby.IPBanCore.IPBanService+<RunCycleAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanService+<RunCycleAsync>d__2, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanService+<RunCycleAsync>d__2, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanService+<RunCycleAsync>d__2, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at DigitalRuby.IPBanCore.IPBanService+<UpdateConfiguration>d__186.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanService+<UpdateConfiguration>d__186, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanService+<UpdateConfiguration>d__186, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanService+<UpdateConfiguration>d__186, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.__Canon>, System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetResult(System.__Canon)
   at DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<CheckForConfigChangeAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<CheckForConfigChangeAsync>d__11, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<CheckForConfigChangeAsync>d__11, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<CheckForConfigChangeAsync>d__11, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at DigitalRuby.IPBanCore.ActionLockerAsync+<LockActionAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.ActionLockerAsync+<LockActionAsync>d__1, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.ActionLockerAsync+<LockActionAsync>d__1, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.ActionLockerAsync+<LockActionAsync>d__1, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<>c__DisplayClass11_0+<<CheckForConfigChangeAsync>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<>c__DisplayClass11_0+<<CheckForConfigChangeAsync>b__0>d, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<>c__DisplayClass11_0+<<CheckForConfigChangeAsync>b__0>d, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<>c__DisplayClass11_0+<<CheckForConfigChangeAsync>b__0>d, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.__Canon>, System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetResult(System.__Canon)
   at DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<ReadConfigAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<ReadConfigAsync>d__9, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<ReadConfigAsync>d__9, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<ReadConfigAsync>d__9, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at DigitalRuby.IPBanCore.ExtensionMethods+<RetryAsync>d__66.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.ExtensionMethods+<RetryAsync>d__66, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.ExtensionMethods+<RetryAsync>d__66, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.ExtensionMethods+<RetryAsync>d__66, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<>c__DisplayClass9_1+<<ReadConfigAsync>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<>c__DisplayClass9_1+<<ReadConfigAsync>b__0>d, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<>c__DisplayClass9_1+<<ReadConfigAsync>b__0>d, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DigitalRuby.IPBanCore.IPBanConfigReaderWriter+<>c__DisplayClass9_1+<<ReadConfigAsync>b__0>d, DigitalRuby.IPBanCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.IO.File+<InternalReadAllTextAsync>d__86.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.File+<InternalReadAllTextAsync>d__86, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.File+<InternalReadAllTextAsync>d__86, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.File+<InternalReadAllTextAsync>d__86, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.IO.StreamReader+<ReadAsyncInternal>d__69.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.IO.StreamReader+<ReadBufferAsync>d__72.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.StreamReader+<ReadBufferAsync>d__72, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.StreamReader+<ReadBufferAsync>d__72, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.StreamReader+<ReadBufferAsync>d__72, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.IO.Strategies.BufferedFileStreamStrategy+<ReadAsyncSlowPath>d__37.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(System.Threading.PortableThreadPool, Boolean ByRef)
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread+StartHelper.RunWorker()
   at System.Threading.Thread+StartHelper.Run()
   at System.Threading.Thread.StartCallback()


Faulting application name: DigitalRuby.IPBan.exe, version: 2.0.1.0, time stamp: 0x6696b883
Faulting module name: DigitalRuby.IPBan.exe, version: 2.0.1.0, time stamp: 0x6696b883
Exception code: 0xc0000005
Fault offset: 0x0000000000229e43
Faulting process id: 0x2428
Faulting application start time: 0x1DB042302803D7A
Faulting application path: H:\Software\IPBan\DigitalRuby.IPBan.exe
Faulting module path: H:\Software\IPBan\DigitalRuby.IPBan.exe
Report Id: de63002f-599f-45eb-81c6-43376a4cef24
Faulting package full name: 
Faulting package-relative application ID:

**Comment by jjxtra** [comment]
Well that nuget package is a bust, though it worked on my local machine and two servers. I rewrote it again with raw PInvoke and updated the 2.0.1 release. Let me know if it helped.

**Comment by fhm20** [comment]
Great! Everything’s working fine. Thanks!
