### ISSUE TITLE
SQLite Error 10: 'disk I/O error'

### ISSUE THREAD

**Issue by mdwin01** [DigitalRuby/IPBan#75]
Hi,

Cool little app!  I installed IPBan in a folder that syncs to Dropbox, so that I could view server logs easily from my laptop, but it seems to cause ipban.sqlite file to throw I/O error.

1) Would it be possible not to save ipban.sqlite every 10 seconds if there are NO changes / new IP's added?
2) After the I/O error IPBan service seems to continue to be running, but no new IP's get detected - I do not see Login succeeded nor Login failure until I manually restart IPBan service.

Thank you!

Mark

```
2019-12-06 08:29:33.5404|ERROR|DigitalRuby.IPBan.IPBanLog|Exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 10: 'disk I/O error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at DigitalRuby.IPBan.SqliteDB.ExecuteNonQuery(String cmdText, SqliteConnection conn, SqliteTransaction tran, Object[] parameters) in C:\Users\Jeff\Documents\GitHub\IPBanPro\IPBan\Core\SqliteDB.cs:line 160
   at DigitalRuby.IPBan.SqliteDB.OpenConnection(SqliteConnection conn) in C:\Users\Jeff\Documents\GitHub\IPBanPro\IPBan\Core\SqliteDB.cs:line 271
   at DigitalRuby.IPBan.SqliteDB.BeginTransaction() in C:\Users\Jeff\Documents\GitHub\IPBanPro\IPBan\Core\SqliteDB.cs:line 353
   at DigitalRuby.IPBan.IPBanService.ProcessPendingLogEvents() in C:\Users\Jeff\Documents\GitHub\IPBanPro\IPBan\Core\IPBanService_Private.cs:line 987
   at DigitalRuby.IPBan.IPBanService.RunCycle() in C:\Users\Jeff\Documents\GitHub\IPBanPro\IPBan\Core\IPBanService.cs:line 82
   at DigitalRuby.IPBan.IPBanService.CycleTimerElapsed(Object sender, ElapsedEventArgs e) in C:\Users\Jeff\Documents\GitHub\IPBanPro\IPBan\Core\IPBanService_Private.cs:line 850
```

**Comment by jjxtra** [comment]
You can set a cycle interval that is longer. Or you can make a scheduled task that copies the SQLite dB and log files to a separate folder and that folder can sync to Dropbox. Hopefully that helps.
