### ISSUE TITLE
ERROR: Value cannot be null. (Parameter 'node')

### ISSUE THREAD

**Issue by SlavikCA** [DigitalRuby/IPBan#83]
I installed IPBan on Windows 2016 Server
Running from elevated PowerShell, not as a service.
I see, that it succefully blocked few IP addresses for failed RDP connections,
But the I see this error in the log:

```
2020-02-10 20:49:58.4756|WARN|DigitalRuby.IPBanCore.Logger|Updating firewall with 1 entries...
2020-02-10 20:51:30.2649|WARN|DigitalRuby.IPBanCore.Logger|Login failure: 68.129.202.154, BJMRKJ, RDP, 3
2020-02-10 20:51:30.3264|WARN|DigitalRuby.IPBanCore.Logger|Login failure: 68.129.202.154, , RDP, 4
2020-02-10 21:04:21.4032|ERROR|DigitalRuby.IPBanCore.Logger|Error Exception: System.ArgumentNullException: Value cannot be null. (Parameter 'node')
   at System.Xml.XmlNodeReader..ctor(XmlNode node)
   at DigitalRuby.IPBanCore.IPBanConfig..ctor(String xml, IDnsLookup dns)
```

Is it real error? Or safe to ignore?

**Comment by jjxtra** [comment]
Can you email me your config or post it here? Feel free to x out any ip addresses or sensitive data...

**Comment by SlavikCA** [comment]
Here it is:

[my.config.txt](https://github.com/DigitalRuby/IPBan/files/4184282/my.config.txt)

I deleted section ` <LogFilesToParse>`, because I don't have any files to parse - only Windows Events. 
Is it the reason for the error?

**Comment by SlavikCA** [comment]
Yes, I had to add this section to get rid of the error:

```
  <LogFilesToParse>
    <LogFiles>
    </LogFiles>
  </LogFilesToParse>
```

**Comment by jjxtra** [comment]
Yes. Just leave it empty for now. Will fix in next update.
